//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leginfor.Models.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cal_t_imss
    {
        public int Id_imss { get; set; }
        public int Ano { get; set; }
        public decimal P_1_1 { get; set; }
        public decimal A_1_1 { get; set; }
        public decimal P_1_2_a { get; set; }
        public Nullable<decimal> A_1_2_a { get; set; }
        public decimal P_1_2_b { get; set; }
        public decimal A_1_2_b { get; set; }
        public decimal P_1_1_1 { get; set; }
        public decimal A_1_1_1 { get; set; }
        public decimal P_2 { get; set; }
        public decimal A_2 { get; set; }
        public decimal P_3 { get; set; }
        public decimal A_3 { get; set; }
        public decimal P_4 { get; set; }
        public decimal A_4 { get; set; }
        public decimal P_5 { get; set; }
        public decimal A_5 { get; set; }
        public decimal P_6 { get; set; }
        public decimal A_6 { get; set; }
    }
}
