//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leginfor.Models.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cal_t_topes
    {
        public int Id_Tope { get; set; }
        public int Id_Tipo { get; set; }
        public System.DateTime fec_ini { get; set; }
        public decimal valor { get; set; }
    }
}
