//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leginfor.Models.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cal_t_limite
    {
        public int Id_limite { get; set; }
        public System.DateTime Fec_Ini { get; set; }
        public decimal Frac_I { get; set; }
        public decimal Frac_II { get; set; }
    }
}
