//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leginfor.Models.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cal_t_art_167
    {
        public int Id_167 { get; set; }
        public decimal minimo { get; set; }
        public decimal maximo { get; set; }
        public decimal basica { get; set; }
        public decimal anual { get; set; }
    }
}
