//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leginfor.Models.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cal_t_isr_new
    {
        public int id_isr { get; set; }
        public int id_periodo { get; set; }
        public int id_fecha { get; set; }
        public decimal inferior { get; set; }
        public decimal superior { get; set; }
        public decimal fija { get; set; }
        public decimal excedente { get; set; }
    }
}
