//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leginfor.Models.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALCULADORA_CAT_MES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CALCULADORA_CAT_MES()
        {
            this.CALCULADORA_CAT_INPC = new HashSet<CALCULADORA_CAT_INPC>();
        }
    
        public int MES_ID { get; set; }
        public string DESCRIPCION { get; set; }
        public string DESC_CORTA { get; set; }
        public short ORDEN { get; set; }
        public bool ACTIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALCULADORA_CAT_INPC> CALCULADORA_CAT_INPC { get; set; }
    }
}
