//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leginfor.Models.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALCULADORA_CAT_INPC
    {
        public int INPC_ID { get; set; }
        public Nullable<int> MES_ID { get; set; }
        public int ANIO { get; set; }
        public double VALOR { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_BAJA { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual CALCULADORA_CAT_MES CALCULADORA_CAT_MES { get; set; }
    }
}
