//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leginfor.Models.ModelBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LEG_CJM_V_IIEntities : DbContext
    {
        public LEG_CJM_V_IIEntities()
            : base("name=LEG_CJM_V_IIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cns_Contenidos> cns_Contenidos { get; set; }
        public virtual DbSet<Clasificacion> Clasificacion { get; set; }
        public virtual DbSet<Estatal> Estatal { get; set; }
        public virtual DbSet<Federal> Federal { get; set; }
        public virtual DbSet<Folio> Folio { get; set; }
        public virtual DbSet<Historico> Historico { get; set; }
        public virtual DbSet<Indice> Indice { get; set; }
        public virtual DbSet<Jurisprudencia> Jurisprudencia { get; set; }
        public virtual DbSet<Noticias> Noticias { get; set; }
        public virtual DbSet<Otros> Otros { get; set; }
        public virtual DbSet<Reformas_Tipos> Reformas_Tipos { get; set; }
        public virtual DbSet<Secciones> Secciones { get; set; }
        public virtual DbSet<Archivos> Archivos { get; set; }
        public virtual DbSet<Reformas> Reformas { get; set; }
        public virtual DbSet<TMP_INDICE> TMP_INDICE { get; set; }
    
        public virtual ObjectResult<sp_TestPresupuestos_Result> sp_TestPresupuestos(string nestado, string estado, string titulo)
        {
            var nestadoParameter = nestado != null ?
                new ObjectParameter("nestado", nestado) :
                new ObjectParameter("nestado", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TestPresupuestos_Result>("sp_TestPresupuestos", nestadoParameter, estadoParameter, tituloParameter);
        }
    
        public virtual int spAdmon_Actualiza_De_cjm()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAdmon_Actualiza_De_cjm");
        }
    
        public virtual int spd_Contenido(Nullable<int> ind_Id, Nullable<decimal> cont_Id, string user_id)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spd_Contenido", ind_IdParameter, cont_IdParameter, user_idParameter);
        }
    
        public virtual int spd_Indice(Nullable<int> ind_Id)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spd_Indice", ind_IdParameter);
        }
    
        public virtual int spd_Noticias(Nullable<short> secc_Id, Nullable<int> noti_Id)
        {
            var secc_IdParameter = secc_Id.HasValue ?
                new ObjectParameter("secc_Id", secc_Id) :
                new ObjectParameter("secc_Id", typeof(short));
    
            var noti_IdParameter = noti_Id.HasValue ?
                new ObjectParameter("noti_Id", noti_Id) :
                new ObjectParameter("noti_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spd_Noticias", secc_IdParameter, noti_IdParameter);
        }
    
        public virtual int spd_Reformas(Nullable<int> ind_Id, Nullable<decimal> cont_Id, Nullable<int> hist_Id, Nullable<int> tpo_Id, Nullable<System.DateTime> ref_Fecha)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            var hist_IdParameter = hist_Id.HasValue ?
                new ObjectParameter("hist_Id", hist_Id) :
                new ObjectParameter("hist_Id", typeof(int));
    
            var tpo_IdParameter = tpo_Id.HasValue ?
                new ObjectParameter("tpo_Id", tpo_Id) :
                new ObjectParameter("tpo_Id", typeof(int));
    
            var ref_FechaParameter = ref_Fecha.HasValue ?
                new ObjectParameter("ref_Fecha", ref_Fecha) :
                new ObjectParameter("ref_Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spd_Reformas", ind_IdParameter, cont_IdParameter, hist_IdParameter, tpo_IdParameter, ref_FechaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spi_clasificacion(string nombre, Nullable<int> orden)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var ordenParameter = orden.HasValue ?
                new ObjectParameter("orden", orden) :
                new ObjectParameter("orden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spi_clasificacion", nombreParameter, ordenParameter);
        }
    
        public virtual ObjectResult<spi_Contenido_Result> spi_Contenido(Nullable<int> ind_Id, Nullable<decimal> cont_Up, Nullable<System.DateTime> cont_Fecha, string cont_Clave, string cont_Titulo_Corto, string cont_Titulo_Indice, string cont_Titulo, string cont_Texto, string cont_Texto_plano, Nullable<int> cla_Id, Nullable<bool> cont_Derogado, Nullable<bool> ver_soloHist, Nullable<bool> cont_Historico, Nullable<System.DateTime> cont_Historico_Fecha, Nullable<bool> cont_Revisado, string user_Id, Nullable<bool> cont_Activo)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_UpParameter = cont_Up.HasValue ?
                new ObjectParameter("cont_Up", cont_Up) :
                new ObjectParameter("cont_Up", typeof(decimal));
    
            var cont_FechaParameter = cont_Fecha.HasValue ?
                new ObjectParameter("cont_Fecha", cont_Fecha) :
                new ObjectParameter("cont_Fecha", typeof(System.DateTime));
    
            var cont_ClaveParameter = cont_Clave != null ?
                new ObjectParameter("cont_Clave", cont_Clave) :
                new ObjectParameter("cont_Clave", typeof(string));
    
            var cont_Titulo_CortoParameter = cont_Titulo_Corto != null ?
                new ObjectParameter("cont_Titulo_Corto", cont_Titulo_Corto) :
                new ObjectParameter("cont_Titulo_Corto", typeof(string));
    
            var cont_Titulo_IndiceParameter = cont_Titulo_Indice != null ?
                new ObjectParameter("cont_Titulo_Indice", cont_Titulo_Indice) :
                new ObjectParameter("cont_Titulo_Indice", typeof(string));
    
            var cont_TituloParameter = cont_Titulo != null ?
                new ObjectParameter("cont_Titulo", cont_Titulo) :
                new ObjectParameter("cont_Titulo", typeof(string));
    
            var cont_TextoParameter = cont_Texto != null ?
                new ObjectParameter("cont_Texto", cont_Texto) :
                new ObjectParameter("cont_Texto", typeof(string));
    
            var cont_Texto_planoParameter = cont_Texto_plano != null ?
                new ObjectParameter("cont_Texto_plano", cont_Texto_plano) :
                new ObjectParameter("cont_Texto_plano", typeof(string));
    
            var cla_IdParameter = cla_Id.HasValue ?
                new ObjectParameter("cla_Id", cla_Id) :
                new ObjectParameter("cla_Id", typeof(int));
    
            var cont_DerogadoParameter = cont_Derogado.HasValue ?
                new ObjectParameter("cont_Derogado", cont_Derogado) :
                new ObjectParameter("cont_Derogado", typeof(bool));
    
            var ver_soloHistParameter = ver_soloHist.HasValue ?
                new ObjectParameter("ver_soloHist", ver_soloHist) :
                new ObjectParameter("ver_soloHist", typeof(bool));
    
            var cont_HistoricoParameter = cont_Historico.HasValue ?
                new ObjectParameter("cont_Historico", cont_Historico) :
                new ObjectParameter("cont_Historico", typeof(bool));
    
            var cont_Historico_FechaParameter = cont_Historico_Fecha.HasValue ?
                new ObjectParameter("cont_Historico_Fecha", cont_Historico_Fecha) :
                new ObjectParameter("cont_Historico_Fecha", typeof(System.DateTime));
    
            var cont_RevisadoParameter = cont_Revisado.HasValue ?
                new ObjectParameter("cont_Revisado", cont_Revisado) :
                new ObjectParameter("cont_Revisado", typeof(bool));
    
            var user_IdParameter = user_Id != null ?
                new ObjectParameter("user_Id", user_Id) :
                new ObjectParameter("user_Id", typeof(string));
    
            var cont_ActivoParameter = cont_Activo.HasValue ?
                new ObjectParameter("cont_Activo", cont_Activo) :
                new ObjectParameter("cont_Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spi_Contenido_Result>("spi_Contenido", ind_IdParameter, cont_UpParameter, cont_FechaParameter, cont_ClaveParameter, cont_Titulo_CortoParameter, cont_Titulo_IndiceParameter, cont_TituloParameter, cont_TextoParameter, cont_Texto_planoParameter, cla_IdParameter, cont_DerogadoParameter, ver_soloHistParameter, cont_HistoricoParameter, cont_Historico_FechaParameter, cont_RevisadoParameter, user_IdParameter, cont_ActivoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spi_Indice(string ind_Titulo, string ind_Texto, Nullable<bool> ind_Historico, Nullable<bool> ind_Revisado, Nullable<bool> ind_Activo)
        {
            var ind_TituloParameter = ind_Titulo != null ?
                new ObjectParameter("ind_Titulo", ind_Titulo) :
                new ObjectParameter("ind_Titulo", typeof(string));
    
            var ind_TextoParameter = ind_Texto != null ?
                new ObjectParameter("ind_Texto", ind_Texto) :
                new ObjectParameter("ind_Texto", typeof(string));
    
            var ind_HistoricoParameter = ind_Historico.HasValue ?
                new ObjectParameter("ind_Historico", ind_Historico) :
                new ObjectParameter("ind_Historico", typeof(bool));
    
            var ind_RevisadoParameter = ind_Revisado.HasValue ?
                new ObjectParameter("ind_Revisado", ind_Revisado) :
                new ObjectParameter("ind_Revisado", typeof(bool));
    
            var ind_ActivoParameter = ind_Activo.HasValue ?
                new ObjectParameter("ind_Activo", ind_Activo) :
                new ObjectParameter("ind_Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spi_Indice", ind_TituloParameter, ind_TextoParameter, ind_HistoricoParameter, ind_RevisadoParameter, ind_ActivoParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> spi_Noticia(Nullable<short> secc_Id, string noti_Titulo, Nullable<System.DateTime> noti_Publicacion, string noti_Contenido, string noti_Fuente, string noti_resumen, Nullable<int> noti_Estado, Nullable<bool> seguridad, Nullable<bool> noti_Activo, string user_Id, Nullable<System.DateTime> est_Actualizado)
        {
            var secc_IdParameter = secc_Id.HasValue ?
                new ObjectParameter("secc_Id", secc_Id) :
                new ObjectParameter("secc_Id", typeof(short));
    
            var noti_TituloParameter = noti_Titulo != null ?
                new ObjectParameter("noti_Titulo", noti_Titulo) :
                new ObjectParameter("noti_Titulo", typeof(string));
    
            var noti_PublicacionParameter = noti_Publicacion.HasValue ?
                new ObjectParameter("noti_Publicacion", noti_Publicacion) :
                new ObjectParameter("noti_Publicacion", typeof(System.DateTime));
    
            var noti_ContenidoParameter = noti_Contenido != null ?
                new ObjectParameter("noti_Contenido", noti_Contenido) :
                new ObjectParameter("noti_Contenido", typeof(string));
    
            var noti_FuenteParameter = noti_Fuente != null ?
                new ObjectParameter("noti_Fuente", noti_Fuente) :
                new ObjectParameter("noti_Fuente", typeof(string));
    
            var noti_resumenParameter = noti_resumen != null ?
                new ObjectParameter("noti_resumen", noti_resumen) :
                new ObjectParameter("noti_resumen", typeof(string));
    
            var noti_EstadoParameter = noti_Estado.HasValue ?
                new ObjectParameter("noti_Estado", noti_Estado) :
                new ObjectParameter("noti_Estado", typeof(int));
    
            var seguridadParameter = seguridad.HasValue ?
                new ObjectParameter("Seguridad", seguridad) :
                new ObjectParameter("Seguridad", typeof(bool));
    
            var noti_ActivoParameter = noti_Activo.HasValue ?
                new ObjectParameter("noti_Activo", noti_Activo) :
                new ObjectParameter("noti_Activo", typeof(bool));
    
            var user_IdParameter = user_Id != null ?
                new ObjectParameter("user_Id", user_Id) :
                new ObjectParameter("user_Id", typeof(string));
    
            var est_ActualizadoParameter = est_Actualizado.HasValue ?
                new ObjectParameter("est_Actualizado", est_Actualizado) :
                new ObjectParameter("est_Actualizado", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("spi_Noticia", secc_IdParameter, noti_TituloParameter, noti_PublicacionParameter, noti_ContenidoParameter, noti_FuenteParameter, noti_resumenParameter, noti_EstadoParameter, seguridadParameter, noti_ActivoParameter, user_IdParameter, est_ActualizadoParameter);
        }
    
        public virtual int spi_Reformas(Nullable<int> ind_Id, Nullable<decimal> cont_Id, Nullable<int> hist_Id, Nullable<int> tpo_Id, Nullable<int> year_Id, Nullable<System.DateTime> ref_Fecha, string ref_Texto)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            var hist_IdParameter = hist_Id.HasValue ?
                new ObjectParameter("hist_Id", hist_Id) :
                new ObjectParameter("hist_Id", typeof(int));
    
            var tpo_IdParameter = tpo_Id.HasValue ?
                new ObjectParameter("tpo_Id", tpo_Id) :
                new ObjectParameter("tpo_Id", typeof(int));
    
            var year_IdParameter = year_Id.HasValue ?
                new ObjectParameter("year_Id", year_Id) :
                new ObjectParameter("year_Id", typeof(int));
    
            var ref_FechaParameter = ref_Fecha.HasValue ?
                new ObjectParameter("ref_Fecha", ref_Fecha) :
                new ObjectParameter("ref_Fecha", typeof(System.DateTime));
    
            var ref_TextoParameter = ref_Texto != null ?
                new ObjectParameter("ref_Texto", ref_Texto) :
                new ObjectParameter("ref_Texto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spi_Reformas", ind_IdParameter, cont_IdParameter, hist_IdParameter, tpo_IdParameter, year_IdParameter, ref_FechaParameter, ref_TextoParameter);
        }
    
        public virtual ObjectResult<sps_Contenido_Result> sps_Contenido(Nullable<int> ind_Id, Nullable<decimal> cont_Id)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Contenido_Result>("sps_Contenido", ind_IdParameter, cont_IdParameter);
        }
    
        public virtual ObjectResult<sps_Contenido_branch_web_Result> sps_Contenido_branch_web(Nullable<decimal> ind_Id, Nullable<decimal> cont_Up)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(decimal));
    
            var cont_UpParameter = cont_Up.HasValue ?
                new ObjectParameter("cont_Up", cont_Up) :
                new ObjectParameter("cont_Up", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Contenido_branch_web_Result>("sps_Contenido_branch_web", ind_IdParameter, cont_UpParameter);
        }
    
        public virtual int sps_Contenido_Buscar(Nullable<decimal> ind_Id, Nullable<decimal> cont_Id, string palabra, Nullable<byte> field, string cadena, string cadena2, string cadena3)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(decimal));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            var palabraParameter = palabra != null ?
                new ObjectParameter("palabra", palabra) :
                new ObjectParameter("palabra", typeof(string));
    
            var fieldParameter = field.HasValue ?
                new ObjectParameter("field", field) :
                new ObjectParameter("field", typeof(byte));
    
            var cadenaParameter = cadena != null ?
                new ObjectParameter("cadena", cadena) :
                new ObjectParameter("cadena", typeof(string));
    
            var cadena2Parameter = cadena2 != null ?
                new ObjectParameter("cadena2", cadena2) :
                new ObjectParameter("cadena2", typeof(string));
    
            var cadena3Parameter = cadena3 != null ?
                new ObjectParameter("cadena3", cadena3) :
                new ObjectParameter("cadena3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sps_Contenido_Buscar", ind_IdParameter, cont_IdParameter, palabraParameter, fieldParameter, cadenaParameter, cadena2Parameter, cadena3Parameter);
        }
    
        public virtual int sps_Contenido_BuscarRediseño(Nullable<decimal> ind_Id, Nullable<decimal> cont_Id, string palabra, Nullable<byte> field, string cadena, string cadena2, string cadena3, Nullable<decimal> numeroPagina, Nullable<decimal> elementosPorPagina)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(decimal));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            var palabraParameter = palabra != null ?
                new ObjectParameter("palabra", palabra) :
                new ObjectParameter("palabra", typeof(string));
    
            var fieldParameter = field.HasValue ?
                new ObjectParameter("field", field) :
                new ObjectParameter("field", typeof(byte));
    
            var cadenaParameter = cadena != null ?
                new ObjectParameter("cadena", cadena) :
                new ObjectParameter("cadena", typeof(string));
    
            var cadena2Parameter = cadena2 != null ?
                new ObjectParameter("cadena2", cadena2) :
                new ObjectParameter("cadena2", typeof(string));
    
            var cadena3Parameter = cadena3 != null ?
                new ObjectParameter("cadena3", cadena3) :
                new ObjectParameter("cadena3", typeof(string));
    
            var numeroPaginaParameter = numeroPagina.HasValue ?
                new ObjectParameter("NumeroPagina", numeroPagina) :
                new ObjectParameter("NumeroPagina", typeof(decimal));
    
            var elementosPorPaginaParameter = elementosPorPagina.HasValue ?
                new ObjectParameter("ElementosPorPagina", elementosPorPagina) :
                new ObjectParameter("ElementosPorPagina", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sps_Contenido_BuscarRediseño", ind_IdParameter, cont_IdParameter, palabraParameter, fieldParameter, cadenaParameter, cadena2Parameter, cadena3Parameter, numeroPaginaParameter, elementosPorPaginaParameter);
        }
    
        public virtual int sps_Contenido_BuscarRediseñobk20120914(Nullable<decimal> ind_Id, Nullable<decimal> cont_Id, string palabra, Nullable<byte> field, string cadena, string cadena2, string cadena3)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(decimal));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            var palabraParameter = palabra != null ?
                new ObjectParameter("palabra", palabra) :
                new ObjectParameter("palabra", typeof(string));
    
            var fieldParameter = field.HasValue ?
                new ObjectParameter("field", field) :
                new ObjectParameter("field", typeof(byte));
    
            var cadenaParameter = cadena != null ?
                new ObjectParameter("cadena", cadena) :
                new ObjectParameter("cadena", typeof(string));
    
            var cadena2Parameter = cadena2 != null ?
                new ObjectParameter("cadena2", cadena2) :
                new ObjectParameter("cadena2", typeof(string));
    
            var cadena3Parameter = cadena3 != null ?
                new ObjectParameter("cadena3", cadena3) :
                new ObjectParameter("cadena3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sps_Contenido_BuscarRediseñobk20120914", ind_IdParameter, cont_IdParameter, palabraParameter, fieldParameter, cadenaParameter, cadena2Parameter, cadena3Parameter);
        }
    
        public virtual int sps_Contenido_BuscarRediseñoPaginacion(Nullable<decimal> ind_Id, Nullable<decimal> cont_Id, string palabra, Nullable<byte> field, string cadena, string cadena2, string cadena3, Nullable<decimal> numeroPagina, Nullable<decimal> elementosPorPagina)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(decimal));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            var palabraParameter = palabra != null ?
                new ObjectParameter("palabra", palabra) :
                new ObjectParameter("palabra", typeof(string));
    
            var fieldParameter = field.HasValue ?
                new ObjectParameter("field", field) :
                new ObjectParameter("field", typeof(byte));
    
            var cadenaParameter = cadena != null ?
                new ObjectParameter("cadena", cadena) :
                new ObjectParameter("cadena", typeof(string));
    
            var cadena2Parameter = cadena2 != null ?
                new ObjectParameter("cadena2", cadena2) :
                new ObjectParameter("cadena2", typeof(string));
    
            var cadena3Parameter = cadena3 != null ?
                new ObjectParameter("cadena3", cadena3) :
                new ObjectParameter("cadena3", typeof(string));
    
            var numeroPaginaParameter = numeroPagina.HasValue ?
                new ObjectParameter("NumeroPagina", numeroPagina) :
                new ObjectParameter("NumeroPagina", typeof(decimal));
    
            var elementosPorPaginaParameter = elementosPorPagina.HasValue ?
                new ObjectParameter("ElementosPorPagina", elementosPorPagina) :
                new ObjectParameter("ElementosPorPagina", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sps_Contenido_BuscarRediseñoPaginacion", ind_IdParameter, cont_IdParameter, palabraParameter, fieldParameter, cadenaParameter, cadena2Parameter, cadena3Parameter, numeroPaginaParameter, elementosPorPaginaParameter);
        }
    
        public virtual ObjectResult<sps_Contenido_indice_WEB_Result> sps_Contenido_indice_WEB(Nullable<int> ind_id, Nullable<int> cont_id)
        {
            var ind_idParameter = ind_id.HasValue ?
                new ObjectParameter("ind_id", ind_id) :
                new ObjectParameter("ind_id", typeof(int));
    
            var cont_idParameter = cont_id.HasValue ?
                new ObjectParameter("cont_id", cont_id) :
                new ObjectParameter("cont_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Contenido_indice_WEB_Result>("sps_Contenido_indice_WEB", ind_idParameter, cont_idParameter);
        }
    
        public virtual int sps_Contenido_Reformas(Nullable<int> ind_Id)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sps_Contenido_Reformas", ind_IdParameter);
        }
    
        public virtual ObjectResult<sps_Contenidos_Result> sps_Contenidos(Nullable<int> ind_Id, Nullable<decimal> cont_Up)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_UpParameter = cont_Up.HasValue ?
                new ObjectParameter("cont_Up", cont_Up) :
                new ObjectParameter("cont_Up", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Contenidos_Result>("sps_Contenidos", ind_IdParameter, cont_UpParameter);
        }
    
        public virtual ObjectResult<sps_Contenidos_Niveles_Result> sps_Contenidos_Niveles(Nullable<int> ind_Id, Nullable<decimal> cont_Up)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_UpParameter = cont_Up.HasValue ?
                new ObjectParameter("cont_Up", cont_Up) :
                new ObjectParameter("cont_Up", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Contenidos_Niveles_Result>("sps_Contenidos_Niveles", ind_IdParameter, cont_UpParameter);
        }
    
        public virtual ObjectResult<sps_Contenidos_Up_Result> sps_Contenidos_Up(Nullable<int> ind_Id, Nullable<decimal> cont_Id)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Contenidos_Up_Result>("sps_Contenidos_Up", ind_IdParameter, cont_IdParameter);
        }
    
        public virtual ObjectResult<sps_Contenidos_WTree_Result> sps_Contenidos_WTree(Nullable<int> ind_Id, Nullable<decimal> cont_Id)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Contenidos_WTree_Result>("sps_Contenidos_WTree", ind_IdParameter, cont_IdParameter);
        }
    
        public virtual ObjectResult<sps_elemento_por_titulo_Result> sps_elemento_por_titulo(Nullable<int> ind_Id, string cont_titulo)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_tituloParameter = cont_titulo != null ?
                new ObjectParameter("cont_titulo", cont_titulo) :
                new ObjectParameter("cont_titulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_elemento_por_titulo_Result>("sps_elemento_por_titulo", ind_IdParameter, cont_tituloParameter);
        }
    
        public virtual ObjectResult<sps_ExportaOrdenamiento_Result> sps_ExportaOrdenamiento(Nullable<int> ind_Id, Nullable<decimal> cont_id)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_idParameter = cont_id.HasValue ?
                new ObjectParameter("cont_id", cont_id) :
                new ObjectParameter("cont_id", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_ExportaOrdenamiento_Result>("sps_ExportaOrdenamiento", ind_IdParameter, cont_idParameter);
        }
    
        public virtual ObjectResult<sps_Federal_Result> sps_Federal(Nullable<int> ind_Id, Nullable<decimal> cont_Id)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Federal_Result>("sps_Federal", ind_IdParameter, cont_IdParameter);
        }
    
        public virtual ObjectResult<sps_FiltrosWeb_Result> sps_FiltrosWeb(Nullable<int> ind_Id, Nullable<decimal> cont_Up)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_UpParameter = cont_Up.HasValue ?
                new ObjectParameter("cont_Up", cont_Up) :
                new ObjectParameter("cont_Up", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_FiltrosWeb_Result>("sps_FiltrosWeb", ind_IdParameter, cont_UpParameter);
        }
    
        public virtual ObjectResult<sps_Historico_lista_Result> sps_Historico_lista(Nullable<int> ind_Id, Nullable<decimal> cont_Id)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Historico_lista_Result>("sps_Historico_lista", ind_IdParameter, cont_IdParameter);
        }
    
        public virtual ObjectResult<sps_Importar_Indice_TreeNet_Result> sps_Importar_Indice_TreeNet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Importar_Indice_TreeNet_Result>("sps_Importar_Indice_TreeNet");
        }
    
        public virtual ObjectResult<sps_Indice_Result> sps_Indice(Nullable<int> ind_Id)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Indice_Result>("sps_Indice", ind_IdParameter);
        }
    
        public virtual ObjectResult<sps_Indices_Result> sps_Indices(Nullable<bool> activo)
        {
            var activoParameter = activo.HasValue ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Indices_Result>("sps_Indices", activoParameter);
        }
    
        public virtual ObjectResult<sps_indiceweb_Result> sps_indiceweb()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_indiceweb_Result>("sps_indiceweb");
        }
    
        public virtual ObjectResult<sps_Inicio_ElementosEstatal_Result> sps_Inicio_ElementosEstatal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Inicio_ElementosEstatal_Result>("sps_Inicio_ElementosEstatal");
        }
    
        public virtual ObjectResult<sps_Inicio_ElementosFederalContratos_Result> sps_Inicio_ElementosFederalContratos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Inicio_ElementosFederalContratos_Result>("sps_Inicio_ElementosFederalContratos");
        }
    
        public virtual ObjectResult<sps_Inicio_ElementosFederalDerogado_Result> sps_Inicio_ElementosFederalDerogado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Inicio_ElementosFederalDerogado_Result>("sps_Inicio_ElementosFederalDerogado");
        }
    
        public virtual ObjectResult<sps_Inicio_ElementosFederalVigente_Result> sps_Inicio_ElementosFederalVigente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Inicio_ElementosFederalVigente_Result>("sps_Inicio_ElementosFederalVigente");
        }
    
        public virtual ObjectResult<sps_Inicio_ElementosJurisprudenciaxEpoca_Result> sps_Inicio_ElementosJurisprudenciaxEpoca()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Inicio_ElementosJurisprudenciaxEpoca_Result>("sps_Inicio_ElementosJurisprudenciaxEpoca");
        }
    
        public virtual ObjectResult<sps_Inicio_ElementosTribunalesxAno_Result> sps_Inicio_ElementosTribunalesxAno()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Inicio_ElementosTribunalesxAno_Result>("sps_Inicio_ElementosTribunalesxAno");
        }
    
        public virtual ObjectResult<sps_Noticias_Result> sps_Noticias(Nullable<short> secc_Id, Nullable<int> noti_Id)
        {
            var secc_IdParameter = secc_Id.HasValue ?
                new ObjectParameter("secc_Id", secc_Id) :
                new ObjectParameter("secc_Id", typeof(short));
    
            var noti_IdParameter = noti_Id.HasValue ?
                new ObjectParameter("noti_Id", noti_Id) :
                new ObjectParameter("noti_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Noticias_Result>("sps_Noticias", secc_IdParameter, noti_IdParameter);
        }
    
        public virtual ObjectResult<Federal> sps_RecuperaID_x_Titulo(Nullable<int> ind_Id, string titulo, Nullable<int> num_Registros)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var num_RegistrosParameter = num_Registros.HasValue ?
                new ObjectParameter("num_Registros", num_Registros) :
                new ObjectParameter("num_Registros", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Federal>("sps_RecuperaID_x_Titulo", ind_IdParameter, tituloParameter, num_RegistrosParameter);
        }
    
        public virtual ObjectResult<Federal> sps_RecuperaID_x_Titulo(Nullable<int> ind_Id, string titulo, Nullable<int> num_Registros, MergeOption mergeOption)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var num_RegistrosParameter = num_Registros.HasValue ?
                new ObjectParameter("num_Registros", num_Registros) :
                new ObjectParameter("num_Registros", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Federal>("sps_RecuperaID_x_Titulo", mergeOption, ind_IdParameter, tituloParameter, num_RegistrosParameter);
        }
    
        public virtual ObjectResult<sps_Reformas_Result> sps_Reformas(Nullable<int> ind_Id, Nullable<decimal> cont_Id, Nullable<int> hist_Id)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            var hist_IdParameter = hist_Id.HasValue ?
                new ObjectParameter("hist_Id", hist_Id) :
                new ObjectParameter("hist_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Reformas_Result>("sps_Reformas", ind_IdParameter, cont_IdParameter, hist_IdParameter);
        }
    
        public virtual int spu_clasificacion(Nullable<int> id, string nombre, Nullable<int> orden)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var ordenParameter = orden.HasValue ?
                new ObjectParameter("orden", orden) :
                new ObjectParameter("orden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spu_clasificacion", idParameter, nombreParameter, ordenParameter);
        }
    
        public virtual int spu_Contenido(Nullable<int> ind_Id, Nullable<decimal> cont_Id, Nullable<System.DateTime> cont_Fecha, string cont_Clave, string cont_Titulo_Corto, string cont_Titulo_Indice, string cont_Titulo, string cont_Texto, string cont_Texto_plano, Nullable<int> cla_Id, Nullable<bool> cont_Derogado, Nullable<bool> ver_soloHist, Nullable<bool> cont_Historico, Nullable<System.DateTime> cont_Historico_Fecha, Nullable<bool> cont_Revisado, string user_Id, Nullable<bool> cont_Activo)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            var cont_FechaParameter = cont_Fecha.HasValue ?
                new ObjectParameter("cont_Fecha", cont_Fecha) :
                new ObjectParameter("cont_Fecha", typeof(System.DateTime));
    
            var cont_ClaveParameter = cont_Clave != null ?
                new ObjectParameter("cont_Clave", cont_Clave) :
                new ObjectParameter("cont_Clave", typeof(string));
    
            var cont_Titulo_CortoParameter = cont_Titulo_Corto != null ?
                new ObjectParameter("cont_Titulo_Corto", cont_Titulo_Corto) :
                new ObjectParameter("cont_Titulo_Corto", typeof(string));
    
            var cont_Titulo_IndiceParameter = cont_Titulo_Indice != null ?
                new ObjectParameter("cont_Titulo_Indice", cont_Titulo_Indice) :
                new ObjectParameter("cont_Titulo_Indice", typeof(string));
    
            var cont_TituloParameter = cont_Titulo != null ?
                new ObjectParameter("cont_Titulo", cont_Titulo) :
                new ObjectParameter("cont_Titulo", typeof(string));
    
            var cont_TextoParameter = cont_Texto != null ?
                new ObjectParameter("cont_Texto", cont_Texto) :
                new ObjectParameter("cont_Texto", typeof(string));
    
            var cont_Texto_planoParameter = cont_Texto_plano != null ?
                new ObjectParameter("cont_Texto_plano", cont_Texto_plano) :
                new ObjectParameter("cont_Texto_plano", typeof(string));
    
            var cla_IdParameter = cla_Id.HasValue ?
                new ObjectParameter("cla_Id", cla_Id) :
                new ObjectParameter("cla_Id", typeof(int));
    
            var cont_DerogadoParameter = cont_Derogado.HasValue ?
                new ObjectParameter("cont_Derogado", cont_Derogado) :
                new ObjectParameter("cont_Derogado", typeof(bool));
    
            var ver_soloHistParameter = ver_soloHist.HasValue ?
                new ObjectParameter("ver_soloHist", ver_soloHist) :
                new ObjectParameter("ver_soloHist", typeof(bool));
    
            var cont_HistoricoParameter = cont_Historico.HasValue ?
                new ObjectParameter("cont_Historico", cont_Historico) :
                new ObjectParameter("cont_Historico", typeof(bool));
    
            var cont_Historico_FechaParameter = cont_Historico_Fecha.HasValue ?
                new ObjectParameter("cont_Historico_Fecha", cont_Historico_Fecha) :
                new ObjectParameter("cont_Historico_Fecha", typeof(System.DateTime));
    
            var cont_RevisadoParameter = cont_Revisado.HasValue ?
                new ObjectParameter("cont_Revisado", cont_Revisado) :
                new ObjectParameter("cont_Revisado", typeof(bool));
    
            var user_IdParameter = user_Id != null ?
                new ObjectParameter("user_Id", user_Id) :
                new ObjectParameter("user_Id", typeof(string));
    
            var cont_ActivoParameter = cont_Activo.HasValue ?
                new ObjectParameter("cont_Activo", cont_Activo) :
                new ObjectParameter("cont_Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spu_Contenido", ind_IdParameter, cont_IdParameter, cont_FechaParameter, cont_ClaveParameter, cont_Titulo_CortoParameter, cont_Titulo_IndiceParameter, cont_TituloParameter, cont_TextoParameter, cont_Texto_planoParameter, cla_IdParameter, cont_DerogadoParameter, ver_soloHistParameter, cont_HistoricoParameter, cont_Historico_FechaParameter, cont_RevisadoParameter, user_IdParameter, cont_ActivoParameter);
        }
    
        public virtual int spu_Contenido_Niveles(Nullable<int> ind_Id, Nullable<decimal> cont_Id, Nullable<int> ind_Id_New, Nullable<int> cont_Id_New, string user_id)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            var ind_Id_NewParameter = ind_Id_New.HasValue ?
                new ObjectParameter("ind_Id_New", ind_Id_New) :
                new ObjectParameter("ind_Id_New", typeof(int));
    
            var cont_Id_NewParameter = cont_Id_New.HasValue ?
                new ObjectParameter("cont_Id_New", cont_Id_New) :
                new ObjectParameter("cont_Id_New", typeof(int));
    
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spu_Contenido_Niveles", ind_IdParameter, cont_IdParameter, ind_Id_NewParameter, cont_Id_NewParameter, user_idParameter);
        }
    
        public virtual int spu_Contenido_Orden(Nullable<int> ind_Id, Nullable<decimal> cont_Id, Nullable<int> posicion)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            var posicionParameter = posicion.HasValue ?
                new ObjectParameter("posicion", posicion) :
                new ObjectParameter("posicion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spu_Contenido_Orden", ind_IdParameter, cont_IdParameter, posicionParameter);
        }
    
        public virtual int spu_Indice(Nullable<int> ind_Id, string ind_Titulo, string ind_Texto, Nullable<bool> ind_Historico, Nullable<bool> ind_Revisado, Nullable<bool> ind_Activo)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var ind_TituloParameter = ind_Titulo != null ?
                new ObjectParameter("ind_Titulo", ind_Titulo) :
                new ObjectParameter("ind_Titulo", typeof(string));
    
            var ind_TextoParameter = ind_Texto != null ?
                new ObjectParameter("ind_Texto", ind_Texto) :
                new ObjectParameter("ind_Texto", typeof(string));
    
            var ind_HistoricoParameter = ind_Historico.HasValue ?
                new ObjectParameter("ind_Historico", ind_Historico) :
                new ObjectParameter("ind_Historico", typeof(bool));
    
            var ind_RevisadoParameter = ind_Revisado.HasValue ?
                new ObjectParameter("ind_Revisado", ind_Revisado) :
                new ObjectParameter("ind_Revisado", typeof(bool));
    
            var ind_ActivoParameter = ind_Activo.HasValue ?
                new ObjectParameter("ind_Activo", ind_Activo) :
                new ObjectParameter("ind_Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spu_Indice", ind_IdParameter, ind_TituloParameter, ind_TextoParameter, ind_HistoricoParameter, ind_RevisadoParameter, ind_ActivoParameter);
        }
    
        public virtual int spu_Noticia(Nullable<int> noti_Id, Nullable<short> secc_Id, string noti_Titulo, Nullable<System.DateTime> noti_Publicacion, string noti_Contenido, string noti_Fuente, string noti_resumen, Nullable<int> noti_Estado, Nullable<bool> seguridad, Nullable<bool> noti_Activo, string user_Id)
        {
            var noti_IdParameter = noti_Id.HasValue ?
                new ObjectParameter("noti_Id", noti_Id) :
                new ObjectParameter("noti_Id", typeof(int));
    
            var secc_IdParameter = secc_Id.HasValue ?
                new ObjectParameter("secc_Id", secc_Id) :
                new ObjectParameter("secc_Id", typeof(short));
    
            var noti_TituloParameter = noti_Titulo != null ?
                new ObjectParameter("noti_Titulo", noti_Titulo) :
                new ObjectParameter("noti_Titulo", typeof(string));
    
            var noti_PublicacionParameter = noti_Publicacion.HasValue ?
                new ObjectParameter("noti_Publicacion", noti_Publicacion) :
                new ObjectParameter("noti_Publicacion", typeof(System.DateTime));
    
            var noti_ContenidoParameter = noti_Contenido != null ?
                new ObjectParameter("noti_Contenido", noti_Contenido) :
                new ObjectParameter("noti_Contenido", typeof(string));
    
            var noti_FuenteParameter = noti_Fuente != null ?
                new ObjectParameter("noti_Fuente", noti_Fuente) :
                new ObjectParameter("noti_Fuente", typeof(string));
    
            var noti_resumenParameter = noti_resumen != null ?
                new ObjectParameter("noti_resumen", noti_resumen) :
                new ObjectParameter("noti_resumen", typeof(string));
    
            var noti_EstadoParameter = noti_Estado.HasValue ?
                new ObjectParameter("noti_Estado", noti_Estado) :
                new ObjectParameter("noti_Estado", typeof(int));
    
            var seguridadParameter = seguridad.HasValue ?
                new ObjectParameter("Seguridad", seguridad) :
                new ObjectParameter("Seguridad", typeof(bool));
    
            var noti_ActivoParameter = noti_Activo.HasValue ?
                new ObjectParameter("noti_Activo", noti_Activo) :
                new ObjectParameter("noti_Activo", typeof(bool));
    
            var user_IdParameter = user_Id != null ?
                new ObjectParameter("user_Id", user_Id) :
                new ObjectParameter("user_Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spu_Noticia", noti_IdParameter, secc_IdParameter, noti_TituloParameter, noti_PublicacionParameter, noti_ContenidoParameter, noti_FuenteParameter, noti_resumenParameter, noti_EstadoParameter, seguridadParameter, noti_ActivoParameter, user_IdParameter);
        }
    }
}
