//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leginfor.Models.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cns_Contenidos
    {
        public decimal Id_Index { get; set; }
        public Nullable<int> ind_Id { get; set; }
        public Nullable<decimal> cont_Id { get; set; }
        public Nullable<decimal> cont_Up { get; set; }
        public Nullable<int> cont_Orden { get; set; }
        public Nullable<System.DateTime> cont_Fecha { get; set; }
        public string cont_Clave { get; set; }
        public string cont_Titulo { get; set; }
        public string cont_Titulo_Corto { get; set; }
        public string cont_Titulo_Indice { get; set; }
        public bool cont_Historico { get; set; }
        public string cont_Texto { get; set; }
        public bool ver_soloHist { get; set; }
        public string cont_Ruta { get; set; }
        public Nullable<int> count_Hijos { get; set; }
        public Nullable<bool> cont_Derogado { get; set; }
        public int cla_Id { get; set; }
        public Nullable<System.DateTime> est_Actualizado { get; set; }
        public Nullable<bool> est_revisado { get; set; }
        public Nullable<System.DateTime> cont_Historico_Fecha { get; set; }
        public bool cont_Activo { get; set; }
    }
}
