//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leginfor.Models.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cnsParrafo
    {
        public decimal do_Id { get; set; }
        public System.DateTime do_Fecha { get; set; }
        public Nullable<int> do_Year { get; set; }
        public Nullable<int> do_Month { get; set; }
        public string do_MonthText { get; set; }
        public Nullable<int> do_Day { get; set; }
        public bool do_Activo { get; set; }
        public int ed_Id { get; set; }
        public string ed_Nombre { get; set; }
        public int secc_Id { get; set; }
        public string secc_Nombre { get; set; }
        public int pod_Id { get; set; }
        public string pod_Nombre { get; set; }
        public int pod_Orden { get; set; }
        public decimal gob_Id { get; set; }
        public string gob_Clave { get; set; }
        public string gob_Nombre { get; set; }
        public int ind_Orden { get; set; }
        public decimal ind_Parrafo { get; set; }
        public decimal parr_Id { get; set; }
        public string parr_Texto { get; set; }
        public int parr_Pagina { get; set; }
        public int parr_Orden { get; set; }
        public int des_id { get; set; }
        public string des_tipo { get; set; }
        public string gob_clave_LG { get; set; }
    }
}
