//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leginfor.Models.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contenido
    {
        public decimal Id_Index { get; set; }
        public Nullable<int> ind_Id { get; set; }
        public Nullable<decimal> cont_Id { get; set; }
        public Nullable<decimal> cont_Up { get; set; }
        public Nullable<int> cont_Orden { get; set; }
        public Nullable<System.DateTime> cont_Fecha { get; set; }
        public string cont_Clave { get; set; }
        public string cont_Titulo_Indice { get; set; }
        public string cont_Titulo_Corto { get; set; }
        public string cont_Titulo { get; set; }
        public string cont_Texto { get; set; }
        public int cat_Id { get; set; }
        public Nullable<int> hist_Id { get; set; }
        public Nullable<int> tpo_id_old { get; set; }
        public Nullable<bool> cont_derogado { get; set; }
        public bool ver_soloHist { get; set; }
        public Nullable<System.DateTime> fecha_tipo_old { get; set; }
        public bool cont_Segunda_temp { get; set; }
        public int Year_Id_Aplica_old { get; set; }
        public bool cont_Historico { get; set; }
        public Nullable<System.DateTime> cont_Historico_fecha { get; set; }
        public Nullable<bool> cont_Revisado { get; set; }
        public System.DateTime est_Actualizado { get; set; }
        public string user_id { get; set; }
        public bool cont_Activo { get; set; }
        public string cont_Texto_plano { get; set; }
        public bool bok { get; set; }
    }
}
