//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leginfor.Models.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equivalencias
    {
        public int apli_Mes { get; set; }
        public int apli_Year { get; set; }
        public System.DateTime equ_Fecha { get; set; }
        public string equ_Pais { get; set; }
        public string equ_Moneda { get; set; }
        public string equ_Valor { get; set; }
    }
}
