//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leginfor.Models.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Extraordinario
    {
        public decimal Ext_Id { get; set; }
        public string Ext_Nombre { get; set; }
        public bool Ext_Activo { get; set; }
        public System.DateTime fec_alt { get; set; }
        public int des_Id { get; set; }
    
        public virtual Destacado Destacado { get; set; }
    }
}
