//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leginfor.Models.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gobierno
    {
        public decimal gob_Id { get; set; }
        public string gob_Clave { get; set; }
        public string gob_clave_LG { get; set; }
        public string gob_Nombre { get; set; }
        public string gob_Archivo { get; set; }
        public int gpo_id { get; set; }
        public bool gob_Activo { get; set; }
    }
}
