//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leginfor.Models.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico
    {
        public decimal Id_Index { get; set; }
        public int ind_Id { get; set; }
        public decimal cont_Id { get; set; }
        public int hist_Id { get; set; }
        public System.DateTime cont_Fecha { get; set; }
        public string cont_Ruta { get; set; }
        public string cont_Clave { get; set; }
        public string cont_Titulo_Corto { get; set; }
        public string cont_Titulo_Indice { get; set; }
        public string cont_Titulo { get; set; }
        public string cont_Texto { get; set; }
        public string cont_Texto_Plano { get; set; }
        public Nullable<bool> cont_derogado { get; set; }
        public bool hist_Activo { get; set; }
    }
}
