//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leginfor.Models.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Indicador()
        {
            this.Valor = new HashSet<Valor>();
        }
    
        public int ind_Id { get; set; }
        public string ind_Nombre { get; set; }
        public string ind_Corto { get; set; }
        public string ind_Largo { get; set; }
        public string ind_Dato1 { get; set; }
        public string ind_Dato2 { get; set; }
        public string ind_Dato3 { get; set; }
        public string ind_Dato4 { get; set; }
        public string ind_Dato5 { get; set; }
        public string ind_Dato6 { get; set; }
        public bool ind_Importe { get; set; }
        public bool ind_Porcentaje { get; set; }
        public int ind_Decimales { get; set; }
        public bool ind_Scroll { get; set; }
        public decimal ind_Valor { get; set; }
        public int tab_Id { get; set; }
        public bool ind_Activo { get; set; }
        public bool Valida_Fecha { get; set; }
        public string formato { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valor> Valor { get; set; }
    }
}
