//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leginfor.Models.ModelBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dofEntities : DbContext
    {
        public dofEntities()
            : base("name=dofEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Destacado> Destacadoes { get; set; }
        public virtual DbSet<Diario> Diarios { get; set; }
        public virtual DbSet<Edicion> Edicions { get; set; }
        public virtual DbSet<Extraordinario> Extraordinarios { get; set; }
        public virtual DbSet<Gobierno> Gobiernoes { get; set; }
        public virtual DbSet<Indice> Indices { get; set; }
        public virtual DbSet<Mes> Meses { get; set; }
        public virtual DbSet<Orden> Ordens { get; set; }
        public virtual DbSet<Poder> Poders { get; set; }
        public virtual DbSet<Seccion> Seccions { get; set; }
        public virtual DbSet<cnsBusqueda> cnsBusquedas { get; set; }
        public virtual DbSet<cnsIndice> cnsIndices { get; set; }
        public virtual DbSet<cnsParrafo> cnsParrafoes { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int Sp_Busca_Conv_Compranet(string docto, Nullable<System.DateTime> f1)
        {
            var doctoParameter = docto != null ?
                new ObjectParameter("docto", docto) :
                new ObjectParameter("docto", typeof(string));
    
            var f1Parameter = f1.HasValue ?
                new ObjectParameter("F1", f1) :
                new ObjectParameter("F1", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Busca_Conv_Compranet", doctoParameter, f1Parameter);
        }
    
        public virtual ObjectResult<Sp_Buscador_Result> Sp_Buscador(string clave, Nullable<System.DateTime> f1)
        {
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            var f1Parameter = f1.HasValue ?
                new ObjectParameter("F1", f1) :
                new ObjectParameter("F1", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Buscador_Result>("Sp_Buscador", claveParameter, f1Parameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<Sps_Buscador_Result> Sps_Buscador(string clave, Nullable<System.DateTime> f1)
        {
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            var f1Parameter = f1.HasValue ?
                new ObjectParameter("F1", f1) :
                new ObjectParameter("F1", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sps_Buscador_Result>("Sps_Buscador", claveParameter, f1Parameter);
        }
    
        public virtual ObjectResult<Sps_Buscador_Legatek_Result> Sps_Buscador_Legatek(string clave, Nullable<System.DateTime> f1)
        {
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            var f1Parameter = f1.HasValue ?
                new ObjectParameter("F1", f1) :
                new ObjectParameter("F1", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sps_Buscador_Legatek_Result>("Sps_Buscador_Legatek", claveParameter, f1Parameter);
        }
    
        public virtual int sps_contenido()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sps_contenido");
        }
    
        public virtual int SPS_Conv_Compranet_Fecha_Dependencia(string dep_Id, string fecha1, string fecha2)
        {
            var dep_IdParameter = dep_Id != null ?
                new ObjectParameter("Dep_Id", dep_Id) :
                new ObjectParameter("Dep_Id", typeof(string));
    
            var fecha1Parameter = fecha1 != null ?
                new ObjectParameter("Fecha1", fecha1) :
                new ObjectParameter("Fecha1", typeof(string));
    
            var fecha2Parameter = fecha2 != null ?
                new ObjectParameter("Fecha2", fecha2) :
                new ObjectParameter("Fecha2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPS_Conv_Compranet_Fecha_Dependencia", dep_IdParameter, fecha1Parameter, fecha2Parameter);
        }
    
        public virtual ObjectResult<Sps_destacado_Result> Sps_destacado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sps_destacado_Result>("Sps_destacado");
        }
    
        public virtual ObjectResult<sps_Diario_Result> sps_Diario(Nullable<System.DateTime> do_Fecha)
        {
            var do_FechaParameter = do_Fecha.HasValue ?
                new ObjectParameter("do_Fecha", do_Fecha) :
                new ObjectParameter("do_Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Diario_Result>("sps_Diario", do_FechaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sps_Diario_InMonth(Nullable<int> id_Year, Nullable<int> id_Month)
        {
            var id_YearParameter = id_Year.HasValue ?
                new ObjectParameter("Id_Year", id_Year) :
                new ObjectParameter("Id_Year", typeof(int));
    
            var id_MonthParameter = id_Month.HasValue ?
                new ObjectParameter("Id_Month", id_Month) :
                new ObjectParameter("Id_Month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sps_Diario_InMonth", id_YearParameter, id_MonthParameter);
        }
    
        public virtual ObjectResult<sps_Diario_Months_Result> sps_Diario_Months(Nullable<int> id_Year)
        {
            var id_YearParameter = id_Year.HasValue ?
                new ObjectParameter("Id_Year", id_Year) :
                new ObjectParameter("Id_Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Diario_Months_Result>("sps_Diario_Months", id_YearParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> sps_Diario_TheLast()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("sps_Diario_TheLast");
        }
    
        public virtual ObjectResult<string> sps_Diario_Years()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sps_Diario_Years");
        }
    
        public virtual ObjectResult<sps_Edicion_Vespertina_Result> sps_Edicion_Vespertina()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Edicion_Vespertina_Result>("sps_Edicion_Vespertina");
        }
    
        public virtual int sps_GetDiariosXMesAnio(string mES, Nullable<int> aNIO)
        {
            var mESParameter = mES != null ?
                new ObjectParameter("MES", mES) :
                new ObjectParameter("MES", typeof(string));
    
            var aNIOParameter = aNIO.HasValue ?
                new ObjectParameter("ANIO", aNIO) :
                new ObjectParameter("ANIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sps_GetDiariosXMesAnio", mESParameter, aNIOParameter);
        }
    
        public virtual ObjectResult<sps_Gobierno_Result> sps_Gobierno()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Gobierno_Result>("sps_Gobierno");
        }
    
        public virtual ObjectResult<sps_Gobierno_Alerta_web_Result> sps_Gobierno_Alerta_web()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Gobierno_Alerta_web_Result>("sps_Gobierno_Alerta_web");
        }
    
        public virtual ObjectResult<sps_Publicacion_Result> sps_Publicacion(Nullable<System.DateTime> do_Fecha)
        {
            var do_FechaParameter = do_Fecha.HasValue ?
                new ObjectParameter("do_Fecha", do_Fecha) :
                new ObjectParameter("do_Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Publicacion_Result>("sps_Publicacion", do_FechaParameter);
        }
    
        public virtual ObjectResult<sps_Publicacion_Sec_Result> sps_Publicacion_Sec(Nullable<System.DateTime> do_Fecha)
        {
            var do_FechaParameter = do_Fecha.HasValue ?
                new ObjectParameter("do_Fecha", do_Fecha) :
                new ObjectParameter("do_Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Publicacion_Sec_Result>("sps_Publicacion_Sec", do_FechaParameter);
        }
    }
}
