//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leginfor.Models.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodo
    {
        public int per_id { get; set; }
        public string per_Name { get; set; }
        public bool per_Activo { get; set; }
        public int tpo_Id { get; set; }
        public string Corto { get; set; }
    }
}
