//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leginfor.Models.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reformas
    {
        public int ind_Id { get; set; }
        public decimal cont_Id { get; set; }
        public int hist_Id { get; set; }
        public int tpo_Id { get; set; }
        public int Year_Id { get; set; }
        public System.DateTime ref_Fecha { get; set; }
        public string ref_Texto { get; set; }
    
        public virtual Reformas_Tipos Reformas_Tipos { get; set; }
    }
}
