//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leginfor.Models.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_paridades_test
    {
        public string Id_Monedad_Test { get; set; }
        public System.DateTime Fecha_Test { get; set; }
        public decimal Paridad_Test { get; set; }
        public Nullable<bool> Fijo_Test { get; set; }
    }
}
