//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leginfor.Models.ModelBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class universoEntities : DbContext
    {
        public universoEntities()
            : base("name=universoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contenido> Contenido { get; set; }
        public virtual DbSet<Noticias> Noticias { get; set; }
        public virtual DbSet<Tipos> Tipos { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int spi_Estadistica(Nullable<int> ind_id, Nullable<decimal> cont_Id, Nullable<int> hist_id, Nullable<int> user_id)
        {
            var ind_idParameter = ind_id.HasValue ?
                new ObjectParameter("ind_id", ind_id) :
                new ObjectParameter("ind_id", typeof(int));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            var hist_idParameter = hist_id.HasValue ?
                new ObjectParameter("hist_id", hist_id) :
                new ObjectParameter("hist_id", typeof(int));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spi_Estadistica", ind_idParameter, cont_IdParameter, hist_idParameter, user_idParameter);
        }
    
        public virtual ObjectResult<string> sps_Claves(Nullable<int> ind_Id, Nullable<int> year_Id)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var year_IdParameter = year_Id.HasValue ?
                new ObjectParameter("Year_Id", year_Id) :
                new ObjectParameter("Year_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sps_Claves", ind_IdParameter, year_IdParameter);
        }
    
        public virtual ObjectResult<sps_Contenido_Result> sps_Contenido(Nullable<int> ind_Id, Nullable<decimal> cont_Id)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Contenido_Result>("sps_Contenido", ind_IdParameter, cont_IdParameter);
        }
    
        public virtual int sps_Contenido_Actualizaciones(Nullable<int> ind_Id)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sps_Contenido_Actualizaciones", ind_IdParameter);
        }
    
        public virtual int sps_Contenido_Actualizaciones_Years(Nullable<int> ind_Id, Nullable<int> year_Id, string cont_Clave)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var year_IdParameter = year_Id.HasValue ?
                new ObjectParameter("Year_Id", year_Id) :
                new ObjectParameter("Year_Id", typeof(int));
    
            var cont_ClaveParameter = cont_Clave != null ?
                new ObjectParameter("cont_Clave", cont_Clave) :
                new ObjectParameter("cont_Clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sps_Contenido_Actualizaciones_Years", ind_IdParameter, year_IdParameter, cont_ClaveParameter);
        }
    
        public virtual ObjectResult<sps_Contenido_branch_web_Result> sps_Contenido_branch_web(Nullable<decimal> ind_Id, Nullable<decimal> cont_Up)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(decimal));
    
            var cont_UpParameter = cont_Up.HasValue ?
                new ObjectParameter("cont_Up", cont_Up) :
                new ObjectParameter("cont_Up", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Contenido_branch_web_Result>("sps_Contenido_branch_web", ind_IdParameter, cont_UpParameter);
        }
    
        public virtual ObjectResult<sps_Contenido_Indice_Result> sps_Contenido_Indice(Nullable<int> ind_Id, Nullable<decimal> cont_Id)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Contenido_Indice_Result>("sps_Contenido_Indice", ind_IdParameter, cont_IdParameter);
        }
    
        public virtual ObjectResult<sps_Contenido_indice_WEB_Result> sps_Contenido_indice_WEB(Nullable<int> ind_id, Nullable<int> cont_id)
        {
            var ind_idParameter = ind_id.HasValue ?
                new ObjectParameter("ind_id", ind_id) :
                new ObjectParameter("ind_id", typeof(int));
    
            var cont_idParameter = cont_id.HasValue ?
                new ObjectParameter("cont_id", cont_id) :
                new ObjectParameter("cont_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Contenido_indice_WEB_Result>("sps_Contenido_indice_WEB", ind_idParameter, cont_idParameter);
        }
    
        public virtual int sps_Contenido_search(Nullable<decimal> ind_Id, Nullable<decimal> cont_Id, string palabra, Nullable<byte> field, string cadena, string cadena2, string cadena3)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(decimal));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            var palabraParameter = palabra != null ?
                new ObjectParameter("palabra", palabra) :
                new ObjectParameter("palabra", typeof(string));
    
            var fieldParameter = field.HasValue ?
                new ObjectParameter("field", field) :
                new ObjectParameter("field", typeof(byte));
    
            var cadenaParameter = cadena != null ?
                new ObjectParameter("cadena", cadena) :
                new ObjectParameter("cadena", typeof(string));
    
            var cadena2Parameter = cadena2 != null ?
                new ObjectParameter("cadena2", cadena2) :
                new ObjectParameter("cadena2", typeof(string));
    
            var cadena3Parameter = cadena3 != null ?
                new ObjectParameter("cadena3", cadena3) :
                new ObjectParameter("cadena3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sps_Contenido_search", ind_IdParameter, cont_IdParameter, palabraParameter, fieldParameter, cadenaParameter, cadena2Parameter, cadena3Parameter);
        }
    
        public virtual ObjectResult<sps_Contenidos_Up_Result> sps_Contenidos_Up(Nullable<int> ind_Id, Nullable<decimal> cont_Id)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Contenidos_Up_Result>("sps_Contenidos_Up", ind_IdParameter, cont_IdParameter);
        }
    
        public virtual ObjectResult<sps_Contenidos_WTree_Result> sps_Contenidos_WTree(Nullable<int> ind_Id, Nullable<decimal> cont_Id)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Contenidos_WTree_Result>("sps_Contenidos_WTree", ind_IdParameter, cont_IdParameter);
        }
    
        public virtual ObjectResult<sps_Historico_Result> sps_Historico(Nullable<int> ind_Id, Nullable<decimal> cont_Id, Nullable<int> hist_Id, Nullable<int> id_Year)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            var hist_IdParameter = hist_Id.HasValue ?
                new ObjectParameter("hist_Id", hist_Id) :
                new ObjectParameter("hist_Id", typeof(int));
    
            var id_YearParameter = id_Year.HasValue ?
                new ObjectParameter("Id_Year", id_Year) :
                new ObjectParameter("Id_Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Historico_Result>("sps_Historico", ind_IdParameter, cont_IdParameter, hist_IdParameter, id_YearParameter);
        }
    
        public virtual ObjectResult<sps_Historico_lista_Result> sps_Historico_lista(Nullable<int> ind_Id, Nullable<decimal> cont_Id)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Historico_lista_Result>("sps_Historico_lista", ind_IdParameter, cont_IdParameter);
        }
    
        public virtual ObjectResult<sps_Historico_Year_Result> sps_Historico_Year(Nullable<int> ind_Id, Nullable<decimal> cont_Id, Nullable<int> id_Year)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            var cont_IdParameter = cont_Id.HasValue ?
                new ObjectParameter("cont_Id", cont_Id) :
                new ObjectParameter("cont_Id", typeof(decimal));
    
            var id_YearParameter = id_Year.HasValue ?
                new ObjectParameter("Id_Year", id_Year) :
                new ObjectParameter("Id_Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Historico_Year_Result>("sps_Historico_Year", ind_IdParameter, cont_IdParameter, id_YearParameter);
        }
    
        public virtual ObjectResult<sps_Noticia_list_Result> sps_Noticia_list(Nullable<int> secc_Id)
        {
            var secc_IdParameter = secc_Id.HasValue ?
                new ObjectParameter("secc_Id", secc_Id) :
                new ObjectParameter("secc_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Noticia_list_Result>("sps_Noticia_list", secc_IdParameter);
        }
    
        public virtual ObjectResult<sps_Noticias_Result> sps_Noticias(Nullable<int> secc_Id, Nullable<decimal> noti_Id)
        {
            var secc_IdParameter = secc_Id.HasValue ?
                new ObjectParameter("secc_Id", secc_Id) :
                new ObjectParameter("secc_Id", typeof(int));
    
            var noti_IdParameter = noti_Id.HasValue ?
                new ObjectParameter("noti_Id", noti_Id) :
                new ObjectParameter("noti_Id", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Noticias_Result>("sps_Noticias", secc_IdParameter, noti_IdParameter);
        }
    
        public virtual ObjectResult<sps_Noticias_Estados_Result> sps_Noticias_Estados(Nullable<int> secc_Id, Nullable<decimal> noti_Id, Nullable<int> edo)
        {
            var secc_IdParameter = secc_Id.HasValue ?
                new ObjectParameter("secc_Id", secc_Id) :
                new ObjectParameter("secc_Id", typeof(int));
    
            var noti_IdParameter = noti_Id.HasValue ?
                new ObjectParameter("noti_Id", noti_Id) :
                new ObjectParameter("noti_Id", typeof(decimal));
    
            var edoParameter = edo.HasValue ?
                new ObjectParameter("edo", edo) :
                new ObjectParameter("edo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Noticias_Estados_Result>("sps_Noticias_Estados", secc_IdParameter, noti_IdParameter, edoParameter);
        }
    
        public virtual ObjectResult<sps_Noticias_Fechas_Result> sps_Noticias_Fechas(Nullable<int> secc_Id, Nullable<System.DateTime> noti_Publicacion)
        {
            var secc_IdParameter = secc_Id.HasValue ?
                new ObjectParameter("secc_Id", secc_Id) :
                new ObjectParameter("secc_Id", typeof(int));
    
            var noti_PublicacionParameter = noti_Publicacion.HasValue ?
                new ObjectParameter("noti_Publicacion", noti_Publicacion) :
                new ObjectParameter("noti_Publicacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Noticias_Fechas_Result>("sps_Noticias_Fechas", secc_IdParameter, noti_PublicacionParameter);
        }
    
        public virtual ObjectResult<sps_Noticias_Months_Result> sps_Noticias_Months(Nullable<int> secc_Id, Nullable<int> year)
        {
            var secc_IdParameter = secc_Id.HasValue ?
                new ObjectParameter("secc_Id", secc_Id) :
                new ObjectParameter("secc_Id", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_Noticias_Months_Result>("sps_Noticias_Months", secc_IdParameter, yearParameter);
        }
    
        public virtual int sps_Year_Id_Aplica_Combo(Nullable<int> ind_Id)
        {
            var ind_IdParameter = ind_Id.HasValue ?
                new ObjectParameter("ind_Id", ind_Id) :
                new ObjectParameter("ind_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sps_Year_Id_Aplica_Combo", ind_IdParameter);
        }
    }
}
