//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leginfor.Models.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valor
    {
        public int ind_Id { get; set; }
        public decimal val_Id { get; set; }
        public System.DateTime val_Fecha_Alta { get; set; }
        public System.DateTime val_Fecha { get; set; }
        public double val_Dato1 { get; set; }
        public double val_Dato2 { get; set; }
        public double val_Dato3 { get; set; }
        public double val_Dato4 { get; set; }
        public double val_Dato5 { get; set; }
        public double val_Dato6 { get; set; }
        public int per_Id1 { get; set; }
        public int per_Id2 { get; set; }
        public int apli_Id { get; set; }
    
        public virtual Indicador Indicador { get; set; }
    }
}
